# Generated by Django 5.2.13 on 2026-04-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_empleado_alter_encomienda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='historialestado',
            old_name='fecha_cambio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.empleado'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='encomienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.encomienda'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='observacion',
            field=models.TextField(blank=True, default='Sin observación'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='empleado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historialestado',
            table=None,
        ),
    ]
