# Generated by Django 5.2.13 on 2026-04-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_empleado_options_alter_historialestado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='encomienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda'),
        ),
    ]
